### PR TITLE
Conda name

### PR DESCRIPTION
**Pull request by t-kimber**
Update README.md instruction for conda file installation.

### TODOs
- [x] Change `toxsmi` to `toxsmi_test`

### Status
- [x] Ready to go

### CODE REVIEW

**Comment by jannisborn** [comment]
Hi @t-kimber, thanks for the PR. I'm not sure I understand why we should rename the conda env in the README?

**Comment by t-kimber** [comment]
The name in the conda.yml file was changed to `toxsmi_test` (see [this line](https://github.com/PaccMann/toxsmi/blob/c9d8079d9c3fb0f6a8741899a68244ae13977a2b/conda.yml#L1)). This means that the conda environment will be called by default `toxsmi_test`with the command `conda env create -f conda.yml` and therefore the readme doesn't coincide anymore.
You could either change the yml file to call the environment toxsmi, or change the readme instruction for the conda installation to 

```
conda env create -n toxsmi -f conda.yml
```
One or the other should be changed for the installation to run smoothly :)

**Comment by jannisborn** [comment]
oh good catch, it seems like this slipped through in #5! 
Let's revert to `toxsmi` in the `.yml` then

**Review by jannisborn — APPROVED** [review]

**Comment by t-kimber** [comment]
Perfect! It's changed :)

**Pull request merged**
